# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Cronograma"
  url = "#logistics"
  weight = 10

[[main]]
  name = "eXploreR"
  url = "#schedule"
  weight = 20

[[main]]
  name = "Tidy Tuesday"
  url = "#tidytuesday"
  weight = 30
  
[[main]]
  name = "Conjuntura"
  url = "#conjuntura"
  weight = 40
  
[[main]]
  name = "Staff"
  url = "#staff"
  weight = 50

#[[main]]
#  name = "Economia"
#  url = "courses/economia/"
#  weight = 60


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
